spring.application.name=makemytrip
server.port=8082

spring.data.mongodb.uri=mongodb+srv://admin:admin@main.v0lhami.mongodb.net/makemytrip?appName=Main
spring.mongodb.uri=mongodb+srv://admin:admin@main.v0lhami.mongodb.net/makemytrip?appName=Main
spring.data.mongodb.database=makemytrip
spring.mongodb.database=makemytrip

spring.data.mongodb.auto-index-creation=true